---
wallets:
  - name: 'USDT (TRC-20)'
    coin: USDT
    network: Tron
    address: 'TJBWYj41pygjd9BiEbuAnWgdbAtg49RcBW'

  - name: 'USDC (TRC-20)'
    coin: USDC
    network: Tron
    address: 'TJBWYj41pygjd9BiEbuAnWgdbAtg49RcBW'

  - name: 'TRX'
    coin: TRX
    network: Tron
    address: 'TJBWYj41pygjd9BiEbuAnWgdbAtg49RcBW'

  - name: 'USDT (BEP-20)'
    coin: USDT
    network: BNB
    address: '0x6Bb095111A0D9f4125a1CDC1ea5a0902fE699Dc9'

  - name: 'USDC (BEP-20)'
    coin: USDC
    network: BNB
    address: '0x6Bb095111A0D9f4125a1CDC1ea5a0902fE699Dc9'

  - name: 'XMR (BEP-20)'
    coin: XMR
    network: BNB
    address: '0x6Bb095111A0D9f4125a1CDC1ea5a0902fE699Dc9'

  - name: 'BNB'
    coin: BNB
    network: BNB
    address: '0x6Bb095111A0D9f4125a1CDC1ea5a0902fE699Dc9'

  - name: 'USDT (Polygon)'
    coin: USDT
    network: Polygon
    address: '0x6Bb095111A0D9f4125a1CDC1ea5a0902fE699Dc9'

  - name: 'USDC (Polygon)'
    coin: USDC
    network: Polygon
    address: '0x6Bb095111A0D9f4125a1CDC1ea5a0902fE699Dc9'

  - name: 'MATIC'
    coin: MATIC
    network: Polygon
    address: '0x6Bb095111A0D9f4125a1CDC1ea5a0902fE699Dc9'

  - name: 'USDT (Solana)'
    coin: USDT
    network: Solana
    address: '9mDiCpp6XPYHYpiDzVLqk7sfSSPoNHGSDd9jfLCdkV59'

  - name: 'USDC (Solana)'
    coin: USDC
    network: Solana
    address: '9mDiCpp6XPYHYpiDzVLqk7sfSSPoNHGSDd9jfLCdkV59'

  - name: 'SOL'
    coin: SOL
    network: Solana
    address: '9mDiCpp6XPYHYpiDzVLqk7sfSSPoNHGSDd9jfLCdkV59'

  - name: 'USDT (ERC-20)'
    coin: USDT
    network: Ethereum
    address: '0x6Bb095111A0D9f4125a1CDC1ea5a0902fE699Dc9'

  - name: 'USDC (ERC-20)'
    coin: USDC
    network: Ethereum
    address: '0x6Bb095111A0D9f4125a1CDC1ea5a0902fE699Dc9'

  - name: 'ETH'
    coin: ETH
    network: Ethereum
    address: '0x6Bb095111A0D9f4125a1CDC1ea5a0902fE699Dc9'

  - name: 'TON'
    coin: TON
    network: TON
    address: 'EQAEmf4FgTykBTRG9bvFl1Qer1fZj89iRjSPCC8eyY5NXCKO'

  - name: 'BTC'
    coin: BTC
    network: Bitcoin
    address: '1PnFSqrKrNbem5JuZK9sVit535FSiEKoNA'

  - name: 'LTC'
    coin: LTC
    network: Litecoin
    address: 'ltc1qqv5ysg4mz4z4mx0kq0nm54pedq0fefk6z674zn'

screen:
  - row:
      - coin: TRX
        network: Tron
      - coin: BNB
        network: BNB
      - coin: ETH
        network: Ethereum
      - coin: MATIC
        network: Polygon
      - coin: SOL
        network: Solana

  - row:
    - coin: USDT
      network: Tron
    - coin: USDT
      network: BNB
    - coin: USDT
      network: Ethereum
    - coin: USDT
      network: Polygon
    - coin: USDT
      network: Solana

  - row:
    - coin: USDC
      network: Tron
    - coin: USDC
      network: BNB
    - coin: USDC
      network: Ethereum
    - coin: USDC
      network: Polygon
    - coin: USDC
      network: Solana

  - row:
      - null
      - coin: XMR
        network: BNB
      - coin: TON
        network: TON
      - coin: BTC
        network: Bitcoin
      - coin: LTC
        network: Litecoin
...
